# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Building

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag portsec-manager:$(date +%s)
